npcEvents:
  - npcId: 10016
    name: Yves
    events:
    - id: "receive_email"
      intro: "Got a surprise invitation to perform at a concert."
      details:
      - "His old phone buzzed unexpectedly with a new message"
      - "Read the concert invitation and froze in disbelief"
      - "Realized the show was in the quiet town he now lived in"
      - "Understood that performing meant the end of anonymity"
    - id: "emotional_response"
      intro: "Reflected on his past and the risks of returning to stage."
      details:
      - "Sat in silence, remembering his fame and what it cost him"
      - "Wondered if this might be his final performance"
      - "Decided to accept the offer despite the fear"
      - "Felt the weight of past expectations return"
    - id: "prepare_disguise"
      intro: "Considered how to avoid recognition during the event."
      details:
      - "Tried on sunglasses and a hat in front of the mirror"
      - "Tested different looks to conceal his identity"
      - "Thought about how to move unseen in public again"
      - "Still unsure if he could truly remain hidden"
    - id: "walk_through_town"
      intro: "Wandered the streets alone, processing the decision."
      details:
      - "Closed his phone and put on his coat"
      - "Walked slowly through DraMai Town under flickering streetlights"
      - "Gazed at the town square where lights shimmered in the distance"
      - "Let the cool night air calm his racing thoughts"
    - id: "discover_box"
      intro: "Found a wooden box in his drawer."
      details:
      - "Opened the drawer after years"
      - "Noticed the wrapping was still intact"
    - id: "open_gift"
      intro: "Unwrapped a memory-filled necklace and card."
      details:
      - "Found a delicate necklace inside"
      - "Recognized the signature from the past"
    - id: "see_email_arrival"
      intro: "Saw the invitation email notification."
      details:
      - "Didn’t open it right away"
      - "Felt a strange anxiety rise"

  - npcId: 10006
    name: Satoshi
    events:
      - id: "old_station_research"
        intro: "Studied EO-777 notes and digital glass map."
        details:
        - "Revealed his face at an abandoned command station"
        - "Claimed he wasn’t a thief but a truth-bearer"
      - id: "meet_musk"
        intro: "Arranged a secret meeting with Musk."
        details:
        - "Showed Musk a shard of digital glass pulsing with the Bitcoin symbol"
        - "Did not activate the map, but left a riddle: Not all lands are meant to be claimed"

  - npcId: 10009
    name: Elon Musk
    events:
      - id: "receive_shard"
        intro: "Received a shard of the Mars map from Satoshi."
        details:
        - "Watched as Satoshi handed over the glowing fragment"
        - "Left pondering the meaning of the riddle"

  - npcId: 10012
    name: Trump
    events:
      - id: "briefcase_breakin"
        intro: "Discovered the EO-777 briefcase was tampered with."
        details:
        - "Papers scattered across the floor, including a Mars land deed"
        - "Security camera feeds suddenly went dark"
        - "Noticed a strange hexadecimal string on the terminal"
      - id: "public_reaction"
        intro: "Responded publicly to the break-in."
        details:
        - "Held a press conference about the land deed leak"
        - "Stormed toward Musk’s rocket lab to confront him"
      - id: "decode_hex"
        intro: "Assembled a team to decipher the hex code."
        details:
        - "Created an AI-led team of expert decoders"
        - "Saw cryptic symbols emerge on the screen"
        - "Grinned darkly while hiding surveillance footage"

  - npcId: 10019
    name: Nina
    events:
      - id: "plan_concert"
        intro: "Prepared her concert materials at her desk."
        details:
        - "Laid out papers and schedules for the upcoming show"
        - "Reflected on her childhood admiration for a pop star"
      - id: "write_invite"
        intro: "Wrote a heartfelt invitation."
        details:
        - "Mentioned a handmade gift she gave as a child"
        - "Felt nervous about contacting him again"
      - id: "send_email"
        intro: "Chose to send the invitation digitally."
        details:
        - "Stood by the postbox, unsure about mailing it"
        - "Decided on email instead, fearing rejection"

